### ISSUE TITLE
Failing under create-react-app dev server

### ISSUE THREAD

**Issue by acbeers** [pocesar/react-use-comlink#2]
When running the example under the create-react-app dev server (started via npm run start), the workers don't work on first load.    However, after editing a source file the workers will start to work.  If you reload the page, the workers again will stop working.

My source code is here: https://github.com/acbeers/worker-test

What I see:

- on first load, the code in useMemo is called twice.  On the first call, the output at line 25 (console.log(res)) shows a resolved promise.  On the second call, the promise is shown as pending.
- when clicking the "Increase from comlink" button, the output at line 31 (console.log(instance)) shows that the promise is still pending.
- after editing the source and saving, useMemo is again called twice.  This time, the output at line 25 shows both promises resolve.  And, the button will now work.

Have you gotten this example to work under cra's development server?  Many thanks for any advice you can offer

**Comment by pocesar** [comment]
@acbeers thanks for the repro. indeed this is caused by strictMode on dev mode, all hooks are called twice. `startAt` will then change from the first render and then the second one, to a total of 4 calls. since hooks are synchronous and promises resolved to the next tick, you'll see this behavior

**Comment by acbeers** [comment]
I am also seeing hooks called twice when running your repo's code with "npm run example".   Added console.log in useMemo and seeing the same thing.  Do you understand why it works there?

**Comment by acbeers** [comment]
OK, yes indeed it is strict mode that's messing things up.  I pushed a change to my example that makes it work - getting useMyClass() outside of components under strict mode was the key.
